app/showcase/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField


# class PurchaseForm(FlaskForm):
#     hash = StringField('hash')
#     submit = SubmitField('submit')

app/showcase/__init__.py
from flask import Blueprint

showcase = Blueprint('showcase', __name__)

from . import views

app/showcase/views.py
from flask import render_template, abort, current_app, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import desc, and_

import app
from app import db
from app.errors import EthereumException
from . import showcase
from app import ethereum_service
from app.models import File, Transaction, Authorization, User, Transfer


@showcase.route('/')
def index():
    files = File.query.filter_by(for_sell=True).order_by(desc(File.time)).all()
    for file in files:
        # TODO: file extension
        file.url = app.upload_files.url(file.hash + '.jpg')
    return render_template('showcase/index.html', files=files)


@showcase.route('/<hash>')
def show_file(hash):
    file = File.query.filter_by(hash=hash).first()
    if file is None:
        abort(404)

    if not file.for_sell:
        if not current_user.is_authenticated:
            abort(403, '请先登录')
        elif not current_user.is_admin() and file.owner_user != current_user:
            authorization = file.authorizations.filter_by(authorized_user=current_user).first()
            if authorization is None:
                abort(403)
            elif not ethereum_service.tx_is_confirmed(authorization.txhash):
                abort(403, '请等待授权完成')

    # TODO fix: file extension
    file_url = app.upload_files.url(file.hash + '.jpg')
    file.is_confirmed = ethereum_service.file_is_confirmed(file)
    file.confirm_num = ethereum_service.get_tx_distance(file.txhash)
    return render_template('showcase/file.html', file=file, file_url=file_url)


@showcase.route('/<hash>/certificate')
def show_certificate(hash):
    file = File.query.filter_by(hash=hash).first()
    if file is None:
        abort(404)

    if file.owner_user != current_user:
        abort(403)

    image_url = app.upload_files.url(file.hash + '.jpg')
    return render_template('showcase/certificate.html', type='作品证书', action='作品登记',
            time=file.time, filename=file.filename, tx_hash=file.txhash, image_url=image_url, username=file.owner)



@showcase.route('/<hash>/purchase', methods=['POST'])
@login_required
def purchase(hash):
    file = File.query.filter_by(hash=hash).first()
    if file is None:
        abort(404, '文件不存在')

    if not ethereum_service.file_is_confirmed(file):
        abort(400, '作品尚未确认，不能购买')

    # 不能购买自己的
    if file.owner_user == current_user:
        abort(400, '不能购买自己的作品')

    if Transaction.query.filter(and_(Transaction.file == file, Transaction.buyer_user == current_user)).first():
        abort(400, '已经购买')

    # 不能购买未出售的
    if not file.for_sell:
        abort(403, '该作品未出售')

    # 检查余额
    balance = ethereum_service.to_ether(ethereum_service.get_balance(current_user.wallets[0].address))
    if balance < file.price:
        abort(400, '余额不足')

    # 写入以太坊
    tx_hash = ethereum_service.purchase(current_user, file)

    # 写入数据库
    transaction = Transaction(seller=file.owner, buyer=current_user.username, file_hash=file.hash, money=file.price,
                              txhash=tx_hash)
    db.session.add(transaction)

    return redirect(url_for('user.transactions'))


@showcase.route('/<hash>/authorize/<to_user>', methods=['POST'])
@login_required
def authorize(hash, to_user):
    file = File.query.filter_by(hash=hash).first()
    if file is None:
        abort(404, '文件不存在')

    to_user_entity = User.query.filter_by(username=to_user).first()
    if not to_user_entity:
        abort(400, '用户名有误')

    # 只能授权自己的的作品
    if file.owner_user != current_user:
        abort(403, '只能授权自己的作品')

    if file.owner_user == to_user_entity:
        abort(400, '不能授权给自己')

    if not ethereum_service.file_is_confirmed(file):
        abort(400, '作品尚未确认，不能授权')

    if Authorization.query.filter(
            and_(Authorization.file == file, Authorization.authorized_username == to_user)).first():
        abort(400, '该用户已经授权')

    # 写入以太坊
    tx_hash = ethereum_service.authorize(current_user, to_user_entity, file)

    # 写入数据库
    authorization = Authorization(file_hash=file.hash, authorizer_username=current_user.username,
                                  authorized_username=to_user,
                                  txhash=tx_hash)
    db.session.add(authorization)

    return redirect(url_for('user.authorizations'))


@showcase.route('/<hash>/transfer/<to_user>', methods=['POST'])
@login_required
def transfer(hash, to_user):
    to_username = to_user
    file = File.query.filter_by(hash=hash).first()
    if file is None:
        abort(404, '文件不存在')

    to_user_entity = User.query.filter_by(username=to_username).first()
    if not to_user_entity:
        abort(400, '用户名有误')

    # 只能转让自己的的作品
    if file.owner_user != current_user:
        abort(403, '只能转让自己的作品')

    if file.owner_user == to_user_entity:
        abort(400, '不能转让给自己')

    if not ethereum_service.file_is_confirmed(file):
        abort(400, '作品尚未确认，不能转让')

    # 写入以太坊
    tx_hash = ethereum_service.transfer(current_user, to_user_entity, file)

    # 写入数据库
    transfer = Transfer(file_hash=file.hash, from_username=current_user.username,
                        to_username=to_username,
                        txhash=tx_hash)
    file.owner = to_username

    db.session.add(transfer)
    db.session.add(file)

    return redirect(url_for('user.transfers'))

app/templates/showcase/certificate.html
{% extends "base.html" %}

{% block title %}
    {{ type }}
{% endblock %}

{% block content_header_title %}
    {{ type }}
{% endblock %}

{% block content_header_description %}
    certificate
{% endblock %}

{% block content %}
    <div class="row">
        <div class="box box-solid">
{#        <div>#}
            <div class="box-body text-center">
                <h2>{{ type }}</h2>
                <div style="margin-top: 48px">
                    <img class="img-responsive " style="max-height: 400px; margin: auto; border: 1px solid rgb(73, 186, 216); padding: 10px" src="{{ image_url }}" alt="Photo">
                </div>
                <p style="font-size: 32px; margin-top: 32px; font-weight: 500">
                    {{ filename }}
                </p>
                <p style="font-size: 24px;" class="text-light-blue">
                    {{ username }}
                </p>
                <p>
                    Copyright © {{ time.year }}
                </p>
                <p>
                    <a href="{{ url_for('ethereum.transaction', tx_hash=tx_hash) }}">  {{ tx_hash }} </a>
                </p>

                <p style="margin-top: 32px">
                    该证书用于证明 <b>{{ username }}</b> 于 {{ time }} 的 {{ action }}
                </p>
            </div>
        </div>
    </div>
 {% endblock %}

{% block script_doc_ready %}
    {{ super() }}
    active_nav(1)
{% endblock %}

app/templates/showcase/file.html
{% extends "base.html" %}

{% block title %}
    作品展示
{% endblock %}

{% block content_header_title %}
    作品展示
{% endblock %}

{% block content_header_description %}
   作品详情
{% endblock %}

{% block levels %}
    <li><a href="#"><i class="fa fa-dashboard"></i>主页</a></li>
    <li><a href="#">作品展示</a></li>
    <li class="active">作品详情</li>
{% endblock %}

{% block content %}
    <div style="margin: auto; width: 720px;">
        <div class="box box-widget">
            <div class="box-header with-border">
                <div class="user-block">
                    <img class="img-circle" src="{{ url_for('static', filename='adminlte/img/user2-160x160.jpg') }}" alt="User Image">
                    <span class="username"><a href="#">{{ file.owner_user.name }}</a></span>
                    <span class="description">{{ file.filename }}</span>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <img class="img-responsive pad" style="margin: auto" src="{{ file_url }}" alt="Photo">

                <div class="pad" id="info">
                    <p>{{ file.description }}</p>

                    <p>
                        {% if file.is_confirmed %}
                            <span class="text-green">已确认({{ file.confirm_num }})</span>
                        {% elif file.confirm_num is not none %}
                            <span class="text-blue">确认中({{ file.confirm_num }})</span>
                        {% else %}
                            <span class="text-yellow">等待确认中</span>
                        {% endif %}
                    </p>
                    <p>
                        <a href="{{ url_for('ethereum.transaction', tx_hash=file.txhash) }}">查看区块链信息</a>
                    </p>

                    {% if file.owner == current_user.username %}
                        <a href="{{ url_for('showcase.show_certificate', hash=file.hash) }}">查看证书</a>
                    {% endif %}

                    {% if file.for_sell and file.owner != current_user.username %}
                        <div class="pull-right">
                            <p style="color: #F40">售价：{{ file.price }} (以太)</p>
                            <form action="{{ url_for('.purchase', hash=file.hash) if file.is_confirmed else 'javascript:void(0);'}}" method="post">
                                <button type="submit" class="btn btn-default btn-xs pull-right {{ 'disabled' if not file.is_confirmed }}" style="color: #f4f4f4; background-color: #F40; border-color: #F40"><i class="fa fa-shopping-cart"></i> 购买</button>
                            </form>
                        </div>
                    {% endif %}

                </div>

            </div>
            <!-- /.box-body -->
        </div>
    </div>
{% endblock %}

{% block script_doc_ready %}
    {{ super() }}
    active_nav(1)
{% endblock %}

app/templates/showcase/index.html
{% extends "base.html" %}

{% block title %}
    作品展示
{% endblock %}

{% block content_header_title %}
    作品展示
{% endblock %}

{% block content_header_description %}
    hello showcase
{% endblock %}

{% block content %}
    <div class="row ">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">上传的作品</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row row-eq-height" >
                    {% for file in files %}
                        {#                        {% for i in range(3) %}#}
                        <div class="col-md-3" style="">
                            <div class="box box-widget">
                                <div class="box-header with-border">
                                    {#                            <a href="{{ url_for('showcase.show_file', hash=file.hash) }}">#}
                                    <b>{{ file.filename }}</b>
                                    {#                            </a>#}
{#                                    {% if current_user == file.owner_user %}#}
{#                                        <div class="box-tools">#}
{#                                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i#}
{#                                                    class="fa fa-times"></i></button>#}
{#                                        </div>#}
{#                                    {% endif %}#}
                                </div>
                                <div class="box-body">
                                    <a href="{{ url_for('showcase.show_file', hash=file.hash) }}">
                                        <img class="img-responsive " style="height: 160px; margin: auto" src="{{ file.url }}"
                                             alt="Photo">
                                    </a>
                                </div>

{#                                <div class="box-footer">#}
{#                                    {{ file.description }}#}
{#                                </div>#}
                            </div>
                        </div>
                        {#                        {% endfor %}#}
                    {% endfor %}
                </div>
            </div>
            <!-- /.box-body -->
        </div>

    </div>
{% endblock %}

{% block script_doc_ready %}
    {{ super() }}
    active_nav(1)
{% endblock %}